# Generated by Django 4.2.4 on 2023-08-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='multiplier',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=5),
        ),
    ]
