# Generated by Django 4.2.4 on 2023-08-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_faqtag_faq_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='asdf-asee'),
            preserve_default=False,
        ),
    ]
