# Generated by Django 4.2.4 on 2023-09-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=50)),
                ('cuz_ID', models.CharField(default='cshowdah', max_length=50)),
                ('cuz_ID_2', models.CharField(default='ebprpmyj', max_length=50)),
                ('time', models.CharField(default='2023-09-07T07:10:39Z', max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
